REGION_NAME = "us-east-1"
STAGE_LAYER_ONE = "ufc-big-data"
STAGE_LAYER_TWO = "ufc-big-data-2"
UFC_META_FILES_LOCATION = "ufc-meta-files"
LOAD_MANIFEST_FOLDER = "ufc-meta-files/load_manifests/"
E1_CSV_OPT_DATE_FOLDER_PATH = "e1-dates"
